---
title: "About me"
---

## Research experience

- Since 2018 DFG Research Fellow - Department of Plant Sciences, University of California Davis, USA  
    [Ross-Ibarra lab](http://rilab.org)
- 2017 Postdoc - Department of Plant Sciences, University of California Davis, USA  
    [Ross-Ibarra lab](http://rilab.org)
- 11/2016 - 01/2017 Research Associate - Crop Biodiversity and Breeding Informatics, University of Hohenheim, Germany  
    [Schmid lab](http://evoplant.uni-hohenheim.de)
- 2013 - 2016 PhD student - Crop Biodiversity and Breeding Informatics, University of Hohenheim, Germany   
    [Schmid lab](http://evoplant.uni-hohenheim.de)
- 2011 - 2013 Master student - Institute of Plant Nutrition, University of Hohenheim, Germany  
  [Ludewig lab](https://scholar.google.de/citations?user=C9ANgTkAAAAJ&hl=en)

## Education

- 2016 PhD - University of Hohenheim, Germany
- 2013 MSc - University of Hohenheim, Germany
- 2011 Guest student - Hebrew University of Jerusalem, Israel
- 2011 BSc - University of Hohenheim, Germany



<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-96594188-1', 'auto');
  ga('send', 'pageview');

</script>